spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motor_parts_hub?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

app:
  client:
    url: http://localhost:4200
